<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\inventory_product; // Using lowercase model name generated by artisan; consider renaming to InventoryProduct for PSR-4 compliance
use Illuminate\Support\Facades\Auth;

class InventoryProductController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $perPage = min(max((int) $request->query('per_page', 15), 1), 100);

        return response()->json(
            inventory_product::latest()->paginate($perPage)
        );
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'cost' => ['required', 'numeric', 'min:0'],
            'quantity' => ['nullable', 'integer', 'min:0'],
            'min_price' => ['required', 'numeric', 'min:0'],
            'mrp' => ['required', 'numeric', 'min:0'],
            'amount' => ['required', 'numeric', 'min:0'],
            'discount' => ['nullable', 'numeric', 'min:0'],
            // frontend may send per-product discount as `product_discount` or `productDiscount`
            'product_discount' => ['nullable', 'numeric', 'min:0'],
            'product_id' => ['required', 'exists:products,id'],
            'inventory_id' => ['required', 'exists:inventories,id'],
            'batch_number' => ['nullable', 'string', 'max:255'],
            'created_by' => ['nullable', 'exists:users,id'],
        ]);

        $data = $validated;
        // map frontend `product_discount` into model `discount` column if provided
        if (array_key_exists('product_discount', $validated)) {
            $data['discount'] = $validated['product_discount'];
        }
        $creatorId = Auth::id() ?: ($data['created_by'] ?? null);
        if (!$creatorId) {
            return response()->json(['message' => 'created_by is required when not authenticated'], 422);
        }
        $data['created_by'] = $creatorId;

        if (array_key_exists('batch_number', $data)) {
            $batch = trim((string)($data['batch_number'] ?? ''));
            $data['batch_number'] = $batch === '' ? null : $batch;
        }

        // defaults
        $data['quantity'] = $data['quantity'] ?? 0;

        $product = inventory_product::create($data);

        return response()->json($product, 201);
    }

    /**
     * Display the specified resource.
     */
    public function show(inventory_product $inventoryProduct)
    {
        return response()->json($inventoryProduct);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, inventory_product $inventoryProduct)
    {
        $validated = $request->validate([
            'cost' => ['sometimes', 'required', 'numeric', 'min:0'],
            'quantity' => ['sometimes', 'nullable', 'integer', 'min:0'],
            'min_price' => ['sometimes', 'required', 'numeric', 'min:0'],
            'mrp' => ['sometimes', 'required', 'numeric', 'min:0'],
            'amount' => ['sometimes', 'required', 'numeric', 'min:0'],
            'product_id' => ['sometimes', 'required', 'exists:products,id'],
            'inventory_id' => ['sometimes', 'required', 'exists:inventories,id'],
            'batch_number' => ['sometimes', 'nullable', 'string', 'max:255'],
            'product_discount' => ['sometimes', 'nullable', 'numeric', 'min:0'],
        ]);

        $data = $validated;
        if (array_key_exists('batch_number', $data)) {
            $batch = trim((string)($data['batch_number'] ?? ''));
            $data['batch_number'] = $batch === '' ? null : $batch;
        }

        // map product_discount to discount for updates
        if (array_key_exists('product_discount', $data)) {
            $data['discount'] = $data['product_discount'];
        }

        $inventoryProduct->update($data);
        return response()->json($inventoryProduct);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(inventory_product $inventoryProduct)
    {
        $inventoryProduct->delete();
        return response()->noContent();
    }
}
